Tutorial sign is now multilanguage
jrddunbr/ElectricalAge pull request #254
Opened 2021-02-13 18:55 UTC by KirillAldashkin

The training sign now supports multilingualism.
The new file structure should look like this:

```
.\EA\
.\EA\tutorialSign\
.\EA\tutorialSign\en_US.txt
.\EA\tutorialSign\<language_code>.txt
.\EA\tutorialSign\...
.\EA\tutorialSign\tutorialSign.txt
```
Where `<language_code>` is "en_US", "ru_RU", "en_UK" etc.

1. If the file `.\EA\tutorialSign\<current_language_code>.txt` exists, it is loaded.
2. Otherwise, if the file `.\EA\tutorialSign\en_US.txt` exists, it is loaded.
3. Otherwise, the file `.\EA\tutorialSign.txt` is loaded.

Support for the  `tutorialSign.txt` the file is left for compatibility.

2021-02-13 19:02 UTC, jrddunbr requested changes

2021-02-13 19:02 UTC, jrddunbr commented on src/main/java/mods/eln/misc/Utils.kt
> +import jdk.nashorn.internal.runtime.Debug
Unnecessary import

2021-02-13 19:02 UTC, jrddunbr commented on src/main/java/mods/eln/misc/Utils.kt
> +import java.io.*
Please replace wildcards with direct imports.

2021-02-13 19:02 UTC, jrddunbr commented on src/main/java/mods/eln/sixnode/tutorialsign/TutorialSignElement.java
> +import scala.Console;
I don't think this import is used.

2021-02-13 19:02 UTC, jrddunbr commented on src/main/java/mods/eln/sixnode/tutorialsign/TutorialSignElement.java
> +            //	e.printStackTrace();
Place `Utils.println("<some error>");` code here for debugging purposes when an exception is thrown.

2021-02-13 19:02 UTC, jrddunbr commented on src/main/java/mods/eln/sixnode/tutorialsign/TutorialSignElement.java
> +            String defaultPath = "EA/tutorialSign/en_US.txt"; //if the localized file is not found, then load the default file (en_US)
Nitpick - please use `.lang` extension and the format used in the language files. Exception permitted for the backwards compat.

2021-02-13 19:02 UTC, jrddunbr commented on src/main/java/mods/eln/sixnode/tutorialsign/TutorialSignElement.java
> +                loadMapFromPath(defaultPath);
Add a `Utils.println()` here that indicates to the developer that they are missing a language if run in debug mode.

2021-02-13 19:50 UTC, jrddunbr commented
Will playtest.

2021-02-13 20:04 UTC, jrddunbr requested changes
Playtesting failed with the testing world. Not sure why. (Notice text in upper left is giving error).

![2021-02-13_15 03 00](https://user-images.githubusercontent.com/14130505/107860314-b927fa80-6e0c-11eb-9890-52aed177cecc.png)

https://github.com/Electrical-Age/ElectricalAge/releases/download/BETA-1.11r51/ElectricalAge_tutorial_map-BETA-1.11r51.zip

2021-02-14 00:45 UTC, KirillAldashkin commented on src/main/java/mods/eln/sixnode/tutorialsign/TutorialSignElement.java
> +            if(file.charAt(0) == '#')
Two record variants are supported:
```
tag1#value 1
#
tag2#
multiline
value 2
```
and
```
#tag1#
value 1
#tag2#
multiline
value 2
```

2021-02-14 01:52 UTC, jrddunbr approved these changes
Playtest successful.

2021-02-14 01:52 UTC, merged